
const ALL_DEPARTMENTS = [
  "Academic Bridging Program",
  "Actuarial Science",
  "American Studies",
  "Anatomy",
  "Anthropology",
  "Archaeology",
  "Architecture and Visual Studies",
  "Art History",
  "Astronomy and Astrophysics​",
  "Biochemistry",
  "Biology",
  "Canadian Institute for Theoretical Astrophysics",
  "Cell and Systems Biology",
  "Centre for Medieval Studies",
  "Chemistry",
  "Cinema Studies Institute",
  "Classics",
  "Cognitive Science",
  "Computer Science",
  "Contemporary Asian Studies, Dr. David Chu Program in",
  "Criminology and Sociolegal Studies, Centre for",
  "Diaspora and Transnational Studies",
  "Drama, Theatre and Performance Studies (Centre for)",
  "Earth Sciences",
  "East Asian Studies",
  "Ecology and Evolutionary Biology",
  "Economics",
  "English",
  "Environment (School of the),",
  "Estonian",
  "Ethics (Centre for)",
  "European Studies",
  "Finnish",
  "First-Year Foundations",
  "Forest Conservation and Forest Biomaterials Science",
  "French",
  "Geography and Planning",
  "German",
  "History",
  "History and Philosophy of Science and Technology",
  "Human Biology",
  "Hungarian",
  "Immunology",
  "Impact Centre",
  "Indigenous Studies",
  "Industrial Relations and Human Res,ources (Centre for)",
  "Innis College",
  "Italian",
  "Centre for Jewish Studies",
  "Laboratory Medicine and Pathobiology",
  "Latin American Studies",
  "Life Sciences",
  "Linguistics",
  "Materials Science",
  "Mathematics",
  "Molecular Genetics and Microbiology",
  "Munk One",
  "Music",
  "Near and Middle Eastern Civilizations",
  "New College",
  "Nutritional Sciences",
  "Peace, Conflict and Justice",
  "Pharmaceutical Chemistry",
  "Pharmacology and Toxicology",
  "Philosophy",
  "Physics",
  "Physiology",
  "Planetary Science",
  "Political Science",
  "Portuguese",
  "Psychology",
  "Public Health Sciences",
  "Public Policy",
  "Religion",
  "Rotman Commerce",
  "St. Michael's College",
  "Sexual Diversity Studies, Mark S. Bonham Centre for",
  "Slavic Languages and Literatures",
  "Sociology",
  "South Asian Studies",
  "Spanish",
  "Statistical Sciences",
  "Trinity College",
  "University College",
  "Victoria College",
  "Women and Gender Studies",
  "Woodsworth College",
  "Yiddish Studies"
];

export default ALL_DEPARTMENTS